<?php

/**
 * @file
 * Language switcher block where untranslated pages link to the frontpage.
 */


/**
 * Implements hook_block_info().
 */
function language_switcher_fallback_block_info() {
  $blocks = array();

  $blocks['language-switcher-fallback'] = array(
    'info' => t('Language Switcher Fallback'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function language_switcher_fallback_block_view($delta = '') {
  $block = array();

  if ($delta == 'language-switcher-fallback' && drupal_multilingual()) {
    $block['subject'] = t('Language Switcher Fallback');

    $path = drupal_is_front_page() ? '<front>' : current_path();
    $links = language_negotiation_get_switch_links(LANGUAGE_TYPE_INTERFACE, $path);

    if (isset($links->links)) {
      drupal_add_css(drupal_get_path('module', 'locale') . '/locale.css');
      $class = "language-switcher-{$links->provider}";
      $variables = array(
        '#links' => $links->links,
        '#attributes' => array('class' => array($class)),
      );
      foreach ($variables['#links'] as $key => $link) {
        if (!isset($link['href'])) {
          $variables['#links'][$key]['href'] = '<front>';
        }
      }

      $variables['#theme'] = 'links__locale_block';

      $block['content'] = render($variables);
    }
  }

  return $block;
}
