<?php
/**
 * @file
 * Code for the FJ16 Base feature.
 */

include_once 'fj16_base.features.inc';

function fj16_import_translation($module, $language) {
  require_once DRUPAL_ROOT . '/includes/locale.inc';

  $translation_dir = drupal_get_path('module', $module) . '/translations';
  
  // Construct file object for PO file
  $file = new stdClass();
  $file->name = $language . '.po';
  $file->uri = $translation_dir . '/' . $file->name;
  $file->filemime = 'application/octet-stream';

  return _locale_import_po($file, $language, LOCALE_IMPORT_OVERWRITE, 'default');
}

function fj16_initialize_node($type, $title, $lang = LANGUAGE_NONE) {
  $node = new stdClass();
  $node->title = $title;
  $node->type = $type;
  node_object_prepare($node);
  $node->language = $lang;
  $node->uid = 1;
  $node->status = 1;
  $node->promote = 0;
  $node->comment = 0;
  return $node;
}

function fj16_user_has_role_named($name) {
  global $user;
  return is_array($user->roles) && in_array($name, $user->roles);
}

function fj16_user_add_role($user, $role_name) {
  if($role = user_role_load_by_name($role_name)) {
    $user->roles[$role->rid] = $role->name;
    return user_save($user);
  }
  return FALSE;
}
