<?php

function fj16_info_articles_update_7002() {
  module_enable(array('tvi'));
}

function fj16_info_articles_update_7003() {
  module_enable(array('i18nviews'));
}

function fj16_info_articles_update_7004() {
  module_enable(array('taxonomy_menu'));
}

function fj16_info_articles_update_7005() {
  module_enable(array('smart_trim'));
}

function fj16_info_articles_update_7006() {
  module_disable(array('taxonomy_menu'));
}
