<?php
/**
 * @file
 * Code for the FJ16 Frontpage boxes feature.
 */

include_once 'fj16_frontpage_boxes.features.inc';

define('FJ16_INSTAGRAM_CLIENT_ID', 'de5ab22ba902466e84feddc6de55d4be');
define('FJ16_INSTAGRAM_CACHE_LIFETIME', 30); // in seconds

function fj16_frontpage_boxes_menu() {
  $menu = array();
  $menu['instajson'] = array(
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'page callback' => '_fj16_frontpage_boxes_get_json',
  	'delivery callback' => '_fj16_frontpage_boxes_deliver_json'
  );
  return $menu;
}

function _fj16_frontpage_boxes_get_json($hashtag) {
  $hashtag = preg_replace("/[^\p{Latin}\-_0-9]/u", "", $hashtag); // remove special characters for security
  $cached = cache_get('fj16_latest_insta_json_' . md5($hashtag));
  if(empty($cached) || _fj16_frontpage_boxes_tag_expired($hashtag)) {
    $json = _fj16_frontpage_boxes_fetch_media_for_tag($hashtag);
    cache_set('fj16_latest_insta_json_' . md5($hashtag), $json);
    return $json;
  } else {
    return $cached->data;
  }
}

function _fj16_frontpage_boxes_deliver_json($json) {
  drupal_add_http_header('Content-Type', 'application/json; charset=utf-8');
  print $json;
}

function _fj16_frontpage_boxes_tag_expired($hashtag) {
  $last_update = _fj16_frontpage_boxes_get_last_updated($hashtag);
  return (time() - $last_update) > FJ16_INSTAGRAM_CACHE_LIFETIME;
}

function _fj16_frontpage_boxes_fetch_media_for_tag($hashtag) {
  $endpoint = 'https://api.instagram.com/v1/tags/';
  $endpoint .= $hashtag;
  $endpoint .= '/media/recent?client_id=';
  $endpoint .= FJ16_INSTAGRAM_CLIENT_ID;

  $json = file_get_contents($endpoint);

  _fj16_frontpage_boxes_set_last_updated($hashtag, time());

  return $json;
}

function _fj16_frontpage_boxes_get_last_updated($hashtag) {
  $vars = variable_get('fj16_insta_last_updated', array());
  return !empty($vars[$hashtag]) ? $vars[$hashtag] : 0;
}

function _fj16_frontpage_boxes_set_last_updated($hashtag, $new_value) {
  $vars = variable_get('fj16_insta_last_updated', array());
  $vars[$hashtag] = $new_value;
  variable_set('fj16_insta_last_updated', $vars);
}
