<?php

// Update hooks that enable necessary features

function fj16_master_update_7001() {
  module_enable(array('fj16_base'));
}

function fj16_master_update_7002() {
  module_enable(array('fj16_frontpage_boxes'));
}

function fj16_master_update_7003() {
  module_enable(array('fj16_basic_content_type'));
}

function fj16_master_update_7004() {
  module_enable(array('fj16_job_ads'));
}

function fj16_master_update_7005() {
  module_enable(array('fj16_programme_and_job_tool'));
}
